spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 10101

dubbo:
  application:
    name: provider
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    basePackages: com.funtl.alibaba.dubbo.provider.service

management:
  endpoints:
    web:
      exposure:
        include: "*"
